# Generated by Django 2.2.19 on 2022-08-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20220809_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='active',
            options={'ordering': ['-date_of_buy'], 'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
    ]
