# Generated by Django 2.2.19 on 2022-08-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20220809_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date_of_buy',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='active',
            name='date_of_sell',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='active',
            name='price_of_sell',
            field=models.FloatField(null=True),
        ),
    ]
