# Generated by Django 2.2.19 on 2022-08-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_auto_20220809_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='date_of_sell',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='active',
            name='price_of_sell',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
