# Generated by Django 2.2.19 on 2022-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_auto_20220809_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
