# Generated by Django 2.2.19 on 2022-08-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_auto_20220809_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AddField(
            model_name='active',
            name='sum_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
