# Generated by Django 2.2.19 on 2022-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_active_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
