# Generated by Django 2.2.19 on 2022-09-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prices', '0015_auto_20220830_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы активов',
            },
        ),
        migrations.CreateModel(
            name='ActiveDistinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('sum_price', models.FloatField(blank=True, null=True)),
                ('result_percent', models.FloatField(blank=True, null=True)),
                ('result_rouble', models.FloatField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('is_block', models.BooleanField()),
                ('is_etf', models.BooleanField()),
                ('is_money', models.BooleanField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activ', to='prices.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activ', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сгруппированный актив',
                'verbose_name_plural': 'Сгруппированные активы',
            },
        ),
    ]
