# Generated by Django 2.2.19 on 2022-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0016_activedistinct_activetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='avg_price',
        ),
        migrations.AlterField(
            model_name='activetype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ActiveDistinct',
        ),
    ]
