# Generated by Django 2.2.19 on 2022-09-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0018_auto_20220907_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='price',
        ),
        migrations.RemoveField(
            model_name='active',
            name='sum_price',
        ),
    ]
