# Generated by Django 2.2.19 on 2022-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0019_auto_20220907_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='sum_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
