# Generated by Django 2.2.19 on 2022-09-08 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0021_active_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='is_block',
        ),
        migrations.RemoveField(
            model_name='active',
            name='is_etf',
        ),
        migrations.RemoveField(
            model_name='active',
            name='is_money',
        ),
        migrations.AlterField(
            model_name='active',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='active',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actives', to='prices.ActiveType'),
        ),
    ]
